aliases:
  - &filter-only-master
    branches:
      only:
        - master

version: 2
jobs:
  deploy-website:
    - image: circleci/node:8.11.1
  steps:
    - checkout
    - run:
        name: Deploying to GitHub Pages
        command: |
          git config --global user.email "$GIT_EMAIL"
          git config --global user.name "$GIT_NAME"
          echo "machine github.com login $GIT_USER password $GITHUB_TOKEN" > ~/.netrc
          cd website && npm install && GIT_USER=$GIT_USER USE_SSH=true npm run publish-gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website:
          filters: *filter-only-master