aliases:
  - &filter-only-master
    branches:
      only:
        - master

version: 2
jobs:
  deploy-website:
    - image: circleci/node:8.11.1
  steps:
    - checkout
    - run:
        name: Deploying to GitHub Pages
        command: |
          git config --global user.email "26461046+frankie-tech@users.noreply.github.com"
          git config --global user.name "Connor W."
          echo "machine github.com login frankie-tech password $GITHUB_TOKEN > ~/.netrc
          cd website && yarn install && GIT_USER=$GIT_USER yarn run publish-gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website:
          filters: *filter-only-master