name: Publish
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.x 
    - name: Set email
      run: git config --global user.email "${{ secrets.adminemail }}"
    - name: Set username
      run: git config --global user.name "${{ secrets.adminname }}"
    - name: NPM install command
      run: cd website && npm install
    - name: check package.json
      run: cat package.json
    - name: Run build command
      run: npm run build
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: move back
      run: cd ..
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: build # The folder the action should deploy.
